// GLFW 3.4 (Win32) as a single translation unit.
#define _GLFW_WIN32

#include "glfw/src/context.c"
#include "glfw/src/init.c"
#include "glfw/src/input.c"
#include "glfw/src/monitor.c"
#include "glfw/src/platform.c"
#include "glfw/src/vulkan.c"
#include "glfw/src/window.c"
#include "glfw/src/egl_context.c"
#include "glfw/src/osmesa_context.c"
#include "glfw/src/win32_module.c"
#include "glfw/src/win32_time.c"
#include "glfw/src/win32_thread.c"
#include "glfw/src/win32_init.c"
#include "glfw/src/win32_joystick.c"
#include "glfw/src/win32_monitor.c"
#include "glfw/src/win32_window.c"
#include "glfw/src/wgl_context.c"
